modLoader="javafml"
loaderVersion="[33,)"
license="Somnia Mod License"
issueTrackerURL="https://github.com/Su5eD/Somnia/issues/"
[[mods]]
modId="somnia"
version="${version}"
displayName="Somnia"
displayURL="https://github.com/Su5eD/Somnia"
logoFile="logo.png"
credits=""
authors="MALfunction84, Kingrunes, Su5eD"
description='''
Simulating the world while you sleep
'''
[[dependencies.somnia]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.somnia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
